/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'deuda_expensas.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'deuda_expensas.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./deuda_expensas.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("departamento").onDelete = 'CASCADE'; 
util.getAttribute("deudaExpensaId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.deudaExpensas",
    options: {
        tableName: "deuda_expensas",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "deudaExpensaId": {
            type: Seq.INTEGER,
            field: "deuda_expensa_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "deuda_expensas_pk"
        },
        "mes": {
            type: Seq.STRING(15),
            field: "mes",
            allowNull: false
        },
        "departamentoId": {
            type: Seq.INTEGER,
            field: "departamento_id",
            allowNull: false,
            references: {
                model: "public.departamentos",
                key: "departamento_id"
            }
        },
        "tarifaExpensaId": {
            type: Seq.INTEGER,
            field: "tarifa_expensa_id",
            allowNull: false,
            references: {
                model: "public.tarifaExpensas",
                key: "tarifa_expensa_id"
            }
        },
        "estado": {
            type: Seq.STRING(25),
            field: "estado",
            allowNull: false
        },
        "pagoExpensaId": {
            type: Seq.INTEGER,
            field: "pago_expensa_id"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.departamentos",
        schema: "public",
        table: "departamentos",
        source: "generator",
        details: {
            as: "departamento",
            foreignKey: "departamento_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.tarifaExpensas",
        schema: "public",
        table: "tarifa_expensas",
        source: "generator",
        details: {
            as: "tarifaExpensa",
            foreignKey: "tarifa_expensa_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};