/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'propietario_departamento.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'propietario_departamento.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./propietario_departamento.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("departamento").onDelete = 'CASCADE'; 
util.getAttribute("propietarioDepartamentoId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.propietarioDepartamento",
    options: {
        tableName: "propietario_departamento",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "propietarioDepartamentoId": {
            type: Seq.INTEGER,
            field: "propietario_departamento_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "propietario_departamento_pk"
        },
        "propietarioId": {
            type: Seq.INTEGER,
            field: "propietario_id",
            references: {
                model: "public.propietarios",
                key: "propietario_id"
            }
        },
        "departamentoId": {
            type: Seq.INTEGER,
            field: "departamento_id",
            references: {
                model: "public.departamentos",
                key: "departamento_id"
            }
        },
        "estado": {
            type: Seq.STRING(50),
            field: "estado"
        },
        "fechaRegistro": {
            type: Seq.DATE,
            field: "fecha_registro"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.departamentos",
        schema: "public",
        table: "departamentos",
        source: "generator",
        details: {
            as: "departamento",
            foreignKey: "departamento_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.propietarios",
        schema: "public",
        table: "propietarios",
        source: "generator",
        details: {
            as: "propietario",
            foreignKey: "propietario_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};