/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'listas.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'listas.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./listas.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("listaId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.listas",
    options: {
        tableName: "listas",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "listaId": {
            type: Seq.INTEGER,
            field: "lista_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "listas_pk"
        },
        "tipo": {
            type: Seq.STRING(250),
            field: "tipo",
            allowNull: false
        },
        "descripcion": {
            type: Seq.STRING(250),
            field: "descripcion",
            allowNull: false
        }
    },
    relations: []
};