/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'usuarios.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'usuarios.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./usuarios.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("usuarioOpcionesLoginFkeys").onDelete = 'CASCADE'; 
util.getAttribute("login").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.usuarios",
    options: {
        tableName: "usuarios",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "login": {
            type: Seq.TEXT,
            field: "login",
            primaryKey: true,
            allowNull: false,
            unique: "usuarios_pkey"
        },
        "password": {
            type: Seq.STRING(50),
            field: "password",
            allowNull: false
        },
        "nombre": {
            type: Seq.STRING(50),
            field: "nombre",
            allowNull: false
        },
        "apellido": {
            type: Seq.STRING(50),
            field: "apellido",
            allowNull: false
        },
        "fechaCreacion": {
            type: Seq.DATE,
            field: "fecha_creacion"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.usuarioOpciones",
        schema: "public",
        table: "usuario_opciones",
        source: "generator",
        details: {
            as: "usuarioOpcionesLoginFkeys",
            foreignKey: "login",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.menuOpciones",
        schema: "public",
        table: "menu_opciones",
        source: "generator",
        details: {
            as: "usuarioOpcionesLoginFkeyMenus",
            foreignKey: "login",
            otherKey: "menu_id",
            through: "usuario_opciones",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};