/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'modelo_depto.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'modelo_depto.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./modelo_depto.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("departamentosModeloIdFkeys").onDelete = 'CASCADE'; 
util.getAttribute("modeloId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.modeloDepto",
    options: {
        tableName: "modelo_depto",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "modeloId": {
            type: Seq.INTEGER,
            field: "modelo_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "modelo_depto_pk"
        },
        "tipo": {
            type: Seq.STRING(50),
            field: "tipo",
            allowNull: false
        },
        "superficie": {
            type: Seq.DECIMAL(5, 2),
            field: "superficie"
        },
        "dormitorios": {
            type: Seq.INTEGER,
            field: "dormitorios",
            allowNull: false
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.departamentos",
        schema: "public",
        table: "departamentos",
        source: "generator",
        details: {
            as: "departamentosModeloIdFkeys",
            foreignKey: "modelo_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.tarifaExpensas",
        schema: "public",
        table: "tarifa_expensas",
        source: "generator",
        details: {
            as: "tarifaExpensasModeloIdFkeys",
            foreignKey: "modelo_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.propietarios",
        schema: "public",
        table: "propietarios",
        source: "generator",
        details: {
            as: "departamentosModeloIdFkeyPropietarios",
            foreignKey: "modelo_id",
            otherKey: "propietario_id",
            through: "departamentos",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};