/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'tarifa_expensas.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'tarifa_expensas.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./tarifa_expensas.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("modeloDepartamento").onDelete = 'CASCADE'; 
util.getAttribute("tarifaExpensaId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.tarifaExpensas",
    options: {
        tableName: "tarifa_expensas",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "tarifaExpensaId": {
            type: Seq.INTEGER,
            field: "tarifa_expensa_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "tarifa_expensas_pk"
        },
        "gestion": {
            type: Seq.STRING(50),
            field: "gestion",
            allowNull: false
        },
        "modeloDepartamentoId": {
            type: Seq.INTEGER,
            field: "modelo_departamento_id",
            references: {
                model: "public.modeloDepartamento",
                key: "modelo_departamento_id"
            }
        },
        "precio": {
            type: Seq.DECIMAL(5, 2),
            field: "precio",
            allowNull: false
        },
        "descripcion": {
            type: Seq.STRING(250),
            field: "descripcion"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.modeloDepartamento",
        schema: "public",
        table: "modelo_departamento",
        source: "generator",
        details: {
            as: "modeloDepartamento",
            foreignKey: "modelo_departamento_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};