/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'egresos.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'egresos.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./egresos.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:

util.getAttribute("egresoId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.egresos",
    options: {
        tableName: "egresos",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "egresoId": {
            type: Seq.INTEGER,
            field: "egreso_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "egresos_pk"
        },
        "fechaEgreso": {
            type: Seq.DATE,
            field: "fecha_egreso"
        },
        "tipoEgreso": {
            type: Seq.STRING(250),
            field: "tipo_egreso",
            allowNull: false
        },
        "descripcion": {
            type: Seq.STRING(500),
            field: "descripcion"
        },
        "totalEgreso": {
            type: Seq.DECIMAL,
            field: "total_egreso",
            allowNull: false
        },
        "numeroComprobante": {
            type: Seq.STRING(250),
            field: "numero_comprobante"
        }
    },
    relations: []
};