/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'usuario_opciones.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'usuario_opciones.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./usuario_opciones.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("relatedLogin").onDelete = 'CASCADE'; 
util.getAttribute("usuarioOpcionId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.usuarioOpciones",
    options: {
        tableName: "usuario_opciones",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "usuarioOpcionId": {
            type: Seq.INTEGER,
            field: "usuario_opcion_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "usuario_opciones_pk"
        },
        "login": {
            type: Seq.TEXT,
            field: "login",
            references: {
                model: "public.usuarios",
                key: "login"
            }
        },
        "menuId": {
            type: Seq.INTEGER,
            field: "menu_id",
            references: {
                model: "public.menuOpciones",
                key: "menu_id"
            }
        },
        "estado": {
            type: Seq.STRING(50),
            field: "estado"
        },
        "fechaRegistro": {
            type: Seq.DATE,
            field: "fecha_registro"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.usuarios",
        schema: "public",
        table: "usuarios",
        source: "generator",
        details: {
            as: "relatedLogin",
            foreignKey: "login",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.menuOpciones",
        schema: "public",
        table: "menu_opciones",
        source: "generator",
        details: {
            as: "menu",
            foreignKey: "menu_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};