/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'deudas.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'deudas.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./deudas.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("pagosDeudaIdFkeys").onDelete = 'CASCADE'; 
util.getAttribute("deudaId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.deudas",
    options: {
        tableName: "deudas",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "deudaId": {
            type: Seq.INTEGER,
            field: "deuda_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "deudas_pk"
        },
        "estructuraTarifariaId": {
            type: Seq.INTEGER,
            field: "estructura_tarifaria_id",
            references: {
                model: "public.estructuraTarifaria",
                key: "estructura_tarifaria_id"
            }
        },
        "tipoTarifa": {
            type: Seq.STRING(100),
            field: "tipo_tarifa",
            allowNull: false
        },
        "precio": {
            type: Seq.DECIMAL(10, 2),
            field: "precio"
        },
        "mes": {
            type: Seq.STRING(15),
            field: "mes"
        },
        "departamentoId": {
            type: Seq.INTEGER,
            field: "departamento_id",
            references: {
                model: "public.departamentos",
                key: "departamento_id"
            }
        },
        "estado": {
            type: Seq.STRING(25),
            field: "estado",
            allowNull: false
        },
        "pagoId": {
            type: Seq.INTEGER,
            field: "pago_id"
        },
        "fechaRegistro": {
            type: Seq.DATE,
            field: "fecha_registro"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.pagos",
        schema: "public",
        table: "pagos",
        source: "generator",
        details: {
            as: "pagosDeudaIdFkeys",
            foreignKey: "deuda_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.departamentos",
        schema: "public",
        table: "departamentos",
        source: "generator",
        details: {
            as: "departamento",
            foreignKey: "departamento_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.estructuraTarifaria",
        schema: "public",
        table: "estructura_tarifaria",
        source: "generator",
        details: {
            as: "estructuraTarifarium",
            foreignKey: "estructura_tarifaria_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};