/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'propietarios.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'propietarios.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./propietarios.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("departamentosPropietarioIdFkeys").onDelete = 'CASCADE'; 
util.getAttribute("propietarioId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.propietarios",
    options: {
        tableName: "propietarios",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "propietarioId": {
            type: Seq.INTEGER,
            field: "propietario_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "propietarios_pk"
        },
        "nombre": {
            type: Seq.STRING(50),
            field: "nombre",
            allowNull: false
        },
        "apellido": {
            type: Seq.STRING(50),
            field: "apellido",
            allowNull: false
        },
        "celular": {
            type: Seq.STRING(10),
            field: "celular"
        },
        "telefono": {
            type: Seq.STRING(10),
            field: "telefono"
        },
        "email": {
            type: Seq.STRING(70),
            field: "email"
        },
        "fechaRegistro": {
            type: Seq.DATE,
            field: "fecha_registro"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.departamentos",
        schema: "public",
        table: "departamentos",
        source: "generator",
        details: {
            as: "departamentosPropietarioIdFkeys",
            foreignKey: "propietario_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "hasMany",
        model: "public.propietarioDepartamento",
        schema: "public",
        table: "propietario_departamento",
        source: "generator",
        details: {
            as: "propietarioDepartamentoPropietarioIdFkeys",
            foreignKey: "propietario_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.modeloDepartamento",
        schema: "public",
        table: "modelo_departamento",
        source: "generator",
        details: {
            as: "departamentosPropietarioIdFkeyModeloDepartamentos",
            foreignKey: "propietario_id",
            otherKey: "modelo_departamento_id",
            through: "departamentos",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};