/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'pagos.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'pagos.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./pagos.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("deuda").onDelete = 'CASCADE'; 
util.getAttribute("pagoId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.pagos",
    options: {
        tableName: "pagos",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "pagoId": {
            type: Seq.INTEGER,
            field: "pago_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "pagos_pk"
        },
        "deudaId": {
            type: Seq.INTEGER,
            field: "deuda_id",
            allowNull: false,
            references: {
                model: "public.deudas",
                key: "deuda_id"
            }
        },
        "tipoTarifa": {
            type: Seq.STRING(50),
            field: "tipo_tarifa"
        },
        "precio": {
            type: Seq.DECIMAL(10, 2),
            field: "precio"
        },
        "fechaRegistro": {
            type: Seq.DATE,
            field: "fecha_registro"
        },
        "pagadoPor": {
            type: Seq.STRING(50),
            field: "pagado_por"
        },
        "observacion": {
            type: Seq.STRING(250),
            field: "observacion"
        }
    },
    relations: [{
        type: "belongsTo",
        model: "public.deudas",
        schema: "public",
        table: "deudas",
        source: "generator",
        details: {
            as: "deuda",
            foreignKey: "deuda_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};