/*jslint node: true */
"use strict";
/*------------------------------------------------------------------------------------

DO NOT EDIT THIS FILE !!! It is generated automatically and will be overwritten.

To modify this model:
1. Create 'departamentos.js' file in 'definition-files-custom' directory located in this file's parent directory.
2. Copy the code below and paste it into 'departamentos.js'.
3. Use utility methods to easily access orm properties.

"use strict";
var orm     = require('model\index.js'),
    model   = require('./departamentos.js'),
    util    = require('../utils.js')(model),
    Seq     = orm.Sequelize();

module.exports = model;

// Some utility methods:
util.getRelation("deudaExpensasDepartamentoIdFkeys").onDelete = 'CASCADE'; 
util.getAttribute("departamentoId").comment = 'This is the comment'; 

------------------------------------------------------------------------------------*/
var orm = require('../index.js'),
    Seq = orm.Sequelize();
module.exports = {
    modelName: "public.departamentos",
    options: {
        tableName: "departamentos",
        schema: "public",
        timestamps: false
    },
    attributes: {
        "departamentoId": {
            type: Seq.INTEGER,
            field: "departamento_id",
            primaryKey: true,
            autoIncrement: true,
            allowNull: false,
            unique: "departamentos_pk"
        },
        "nombre": {
            type: Seq.STRING(50),
            field: "nombre"
        },
        "modeloDepartamentoId": {
            type: Seq.INTEGER,
            field: "modelo_departamento_id",
            references: {
                model: "public.modeloDepartamento",
                key: "modelo_departamento_id"
            }
        },
        "propietarioId": {
            type: Seq.INTEGER,
            field: "propietario_id",
            references: {
                model: "public.propietarios",
                key: "propietario_id"
            }
        },
        "cantidadHabitantes": {
            type: Seq.INTEGER,
            field: "cantidad_habitantes"
        },
        "fechaRegistro": {
            type: Seq.DATE,
            field: "fecha_registro"
        }
    },
    relations: [{
        type: "hasMany",
        model: "public.deudaExpensas",
        schema: "public",
        table: "deuda_expensas",
        source: "generator",
        details: {
            as: "deudaExpensasDepartamentoIdFkeys",
            foreignKey: "departamento_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.modeloDepartamento",
        schema: "public",
        table: "modelo_departamento",
        source: "generator",
        details: {
            as: "modeloDepartamento",
            foreignKey: "modelo_departamento_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsTo",
        model: "public.propietarios",
        schema: "public",
        table: "propietarios",
        source: "generator",
        details: {
            as: "propietario",
            foreignKey: "propietario_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }, {
        type: "belongsToMany",
        model: "public.tarifaExpensas",
        schema: "public",
        table: "tarifa_expensas",
        source: "generator",
        details: {
            as: "deudaExpensasDepartamentoIdFkeyTarifaExpensas",
            foreignKey: "departamento_id",
            otherKey: "tarifa_expensa_id",
            through: "deuda_expensas",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }]
};